// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyC1KdPPeKa5DxiKcWYINtXnFWQTG9ZfquQ',
//     appId: '1:802168313951:web:e21db6e76ec9ae4c06e3ea',
//     messagingSenderId: '802168313951',
//     projectId: 'signupandsignin-689dc',
//     authDomain: 'signupandsignin-689dc.firebaseapp.com',
//     storageBucket: 'signupandsignin-689dc.appspot.com',
//     measurementId: 'G-Z9Y8F3K9WJ',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyA2niXwXpgRPLIuNSg7Lv3zLmR_dSS4YtE',
//     appId: '1:802168313951:android:3dfc5212bbed225a06e3ea',
//     messagingSenderId: '802168313951',
//     projectId: 'signupandsignin-689dc',
//     storageBucket: 'signupandsignin-689dc.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAwd4ev9JjVYxo8bNv_7V__4jjEazBzkb8',
//     appId: '1:802168313951:ios:69fcf4adf7d8224206e3ea',
//     messagingSenderId: '802168313951',
//     projectId: 'signupandsignin-689dc',
//     storageBucket: 'signupandsignin-689dc.appspot.com',
//     iosBundleId: 'com.example.loginsignup',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAwd4ev9JjVYxo8bNv_7V__4jjEazBzkb8',
//     appId: '1:802168313951:ios:641a355aeeda7f5306e3ea',
//     messagingSenderId: '802168313951',
//     projectId: 'signupandsignin-689dc',
//     storageBucket: 'signupandsignin-689dc.appspot.com',
//     iosBundleId: 'com.example.loginsignup.RunnerTests',
//   );
// }
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsY2AzaacnaFh7p9oK_zU2tYKlhiyhBLw',
    appId: '1:901449356823:web:0f4735b2cd459f00ab2e52',
    messagingSenderId: '901449356823',
    projectId: 'eventsy-e3944',
    authDomain: 'eventsy-e3944.firebaseapp.com',
    storageBucket: 'eventsy-e3944.appspot.com',
    measurementId: 'G-X00B4BRKE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUZT0NjjWMAOv3qLGpfkKZp5Z4CzJEyPw',
    appId: '1:901449356823:android:72e9a81a92013692ab2e52',
    messagingSenderId: '901449356823',
    projectId: 'eventsy-e3944',
    storageBucket: 'eventsy-e3944.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH25kjTkpkRDNNnc0JgTZ0R4Vk0etio2k',
    appId: '1:901449356823:ios:6062addd663d85fcab2e52',
    messagingSenderId: '901449356823',
    projectId: 'eventsy-e3944',
    storageBucket: 'eventsy-e3944.appspot.com',
    iosClientId:
        '901449356823-kaljsitvgolmpk4seir0ejio58imfn2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventsy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH25kjTkpkRDNNnc0JgTZ0R4Vk0etio2k',
    appId: '1:901449356823:ios:3d2ae6d71a8f5c7cab2e52',
    messagingSenderId: '901449356823',
    projectId: 'eventsy-e3944',
    storageBucket: 'eventsy-e3944.appspot.com',
    iosClientId:
        '901449356823-gv8bc4vic5bfhnq3emv1mp1n5tlrb7sn.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventsy.RunnerTests',
  );
}
