// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXb0utVGvXDeVVaL6sC-Msg8DS8jM9Pb4',
    appId: '1:667846412743:web:db56e48b853e8315bbb1e2',
    messagingSenderId: '667846412743',
    projectId: 'eventsy-f9d80',
    authDomain: 'eventsy-f9d80.firebaseapp.com',
    storageBucket: 'eventsy-f9d80.appspot.com',
    measurementId: 'G-PYYGSRQJKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf7lr7G6st7iLA7umMqJ9epMcIXKt-S8A',
    appId: '1:667846412743:android:1eb8d455c5c8bcd6bbb1e2',
    messagingSenderId: '667846412743',
    projectId: 'eventsy-f9d80',
    storageBucket: 'eventsy-f9d80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgiJu29PK02sMxhu7UJfgEXFxtb3fNVJ4',
    appId: '1:667846412743:ios:9592001508d97849bbb1e2',
    messagingSenderId: '667846412743',
    projectId: 'eventsy-f9d80',
    storageBucket: 'eventsy-f9d80.appspot.com',
    iosClientId: '667846412743-ql0k7bpt3smmo6ne6cjribvv6hsq6124.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventsy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgiJu29PK02sMxhu7UJfgEXFxtb3fNVJ4',
    appId: '1:667846412743:ios:a6b71e6d3a03d601bbb1e2',
    messagingSenderId: '667846412743',
    projectId: 'eventsy-f9d80',
    storageBucket: 'eventsy-f9d80.appspot.com',
    iosClientId: '667846412743-pm4f9o9crgctm3d2qdq3jj1r8e61vi07.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventsy.RunnerTests',
  );
}
